# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfridge', '0002_ingredient_shelflife'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='qty_suffix',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
