# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfridge', '0003_ingredient_qty_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='temperature',
            field=models.CharField(default='refrigerate', max_length=16),
            preserve_default=False,
        ),
    ]
